{
 "title": "dash-forum-api",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "application", "label": "application", "query": { "query": "label_values(application)" } },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(jvm_classes_loaded_classes{application=\"$application\"},instance)"
    }
   },
   {
    "name": "pool",
    "label": "pool",
    "query": {
     "query": "label_values(hikaricp_connections{instance=\"$instance\", application=\"$application\"}, pool)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "API BASIC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "UPTIME",
     "type": "stat",
     "description": "API uptime",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "dthms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_uptime_seconds{application=\"$application\", instance=\"$instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "USERS LOGGED LAST MIN",
     "type": "stat",
     "description": "Usuários logados no último minuto",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(auth_user_success_total[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "JDBC POOL",
     "type": "stat",
     "description": "Pool de conexões JDBC",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "hikaricp_connections{application=\"$application\",instance=\"$instance\", pool=\"$pool\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CONNECTION STATE",
     "type": "timeseries",
     "description": "Estado das conexões com o database",
     "gridPos": { "h": 6, "w": 15, "x": 9, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "hikaricp_connections_active{application=\"$application\",instance=\"$instance\",pool=\"$pool\"}",
       "legendFormat": "active"
      },
      {
       "expr": "hikaricp_connections_idle{application=\"$application\",instance=\"$instance\",pool=\"$pool\"}",
       "legendFormat": "idle"
      },
      {
       "expr": "hikaricp_connections_pending{application=\"$application\",instance=\"$instance\",pool=\"$pool\"}",
       "legendFormat": "pending"
      }
     ]
    },
    {
     "title": "START TIME",
     "type": "stat",
     "description": "Hora da inicialização da API",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsLocalNoDateIfToday" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_start_time_seconds{application=\"$application\", instance=\"$instance\"} * 1000",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "AUTH ERRORS LAST MIN",
     "type": "stat",
     "description": "Erros de autenticação no último minuto",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(auth_user_error_total[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "DB TIMEOUT LAST MIN",
     "type": "stat",
     "description": "Conexões com o database em timeout no último minuto",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(hikaricp_connections_timeout_total{application=\"$application\", instance=\"$instance\", pool=\"$pool\"}[1m])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "WARN & ERROR LOG",
     "type": "timeseries",
     "description": "Warnings e erros logados nos últimos 5 minutos",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(logback_events_total{application=\"$application\", instance=\"$instance\",level=\"warn\"}[5m]))",
       "legendFormat": "warn"
      },
      {
       "expr": "sum(increase(logback_events_total{application=\"$application\", instance=\"$instance\",level=\"error\"}[5m]))",
       "legendFormat": "error"
      }
     ]
    }
   ]
  },
  {
   "title": "API RED",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "TOTAL REQUESTS IN THE LAST MIN",
     "type": "stat",
     "description": "Número de requisições",
     "gridPos": { "h": 3, "w": 5, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", uri!=\"/actuator/prometheus\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "ERROR 500 LAST MIN",
     "type": "stat",
     "description": "Número de erros 500 no último minuto",
     "gridPos": { "h": 3, "w": 5, "x": 5, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", uri!=\"/actuator/prometheus\", status=\"500\"}[1m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "LATENCY AVERAGE",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 14, "x": 10, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", instance=\"$instance\", uri!=\"/actuator/prometheus\"}[1m])) by (le))",
       "legendFormat": "99%"
      },
      {
       "expr": "histogram_quantile(0.9, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", instance=\"$instance\", uri!=\"/actuator/prometheus\"}[1m])) by (le))",
       "legendFormat": "90%"
      },
      {
       "expr": "histogram_quantile(0.75, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", instance=\"$instance\", uri!=\"/actuator/prometheus\"}[1m])) by (le))",
       "legendFormat": "75%"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", instance=\"$instance\", uri!=\"/actuator/prometheus\"}[1m])) by (le))",
       "legendFormat": "50%"
      },
      {
       "expr": "histogram_quantile(0.25, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", instance=\"$instance\", uri!=\"/actuator/prometheus\"}[1m])) by (le))",
       "legendFormat": "25%"
      }
     ]
    },
    {
     "title": "ERROR RATE",
     "type": "timeseries",
     "description": "Taxa de erro nos últimos 5 minutos",
     "gridPos": { "h": 13, "w": 10, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", uri!=\"/actuator/prometheus\", status=\"500\"}[5m])) / sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", uri!=\"/actuator/prometheus\"}[5m]))",
       "legendFormat": "500"
      },
      {
       "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", uri!=\"/actuator/prometheus\", status=\"400\"}[5m])) / sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", uri!=\"/actuator/prometheus\"}[5m]))",
       "legendFormat": "400"
      },
      {
       "expr": "sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", uri!=\"/actuator/prometheus\", status=\"404\"}[5m])) / sum(rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", uri!=\"/actuator/prometheus\"}[5m]))",
       "legendFormat": "404"
      }
     ]
    },
    {
     "title": "RESPONSE TIME LAST MIN",
     "type": "timeseries",
     "description": "Tempo de resposta no último minuto",
     "gridPos": { "h": 9, "w": 14, "x": 10, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(http_server_requests_seconds_sum{application=\"$application\",instance=\"$instance\",uri!=\"/actuator/prometheus\"}[1m]) / rate(http_server_requests_seconds_count{application=\"$application\",instance=\"$instance\",uri!=\"/actuator/prometheus\"}[1m])",
       "legendFormat": "{{uri}} {{method}} {{status}}"
      }
     ]
    },
    {
     "title": "REQUEST COUNT LAST MIN",
     "type": "timeseries",
     "description": "Número de requisições por endpoint no último minuto",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", uri=\"/topicos\"}[1m]))",
       "legendFormat": "/topicos"
      },
      {
       "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", uri=\"/topicos/{id}\"}[1m]))",
       "legendFormat": "/topicos/{id}"
      },
      {
       "expr": "sum(increase(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", uri=\"/auth\"}[1m]))",
       "legendFormat": "/auth"
      }
     ]
    },
    {
     "title": "AVERAGE REQUEST DURATION LAST MIN",
     "type": "timeseries",
     "description": "Duração média de requisições no último minuto",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(http_server_requests_seconds_sum{application=\"$application\", instance=\"$instance\", status=\"200\", uri=\"/topicos\"}[1m]) / rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", status=\"200\", uri=\"/topicos\"}[1m])",
       "legendFormat": "{{uri}} {{method}} {{status}}"
      },
      {
       "expr": "rate(http_server_requests_seconds_sum{application=\"$application\", instance=\"$instance\", status=\"200\", uri=\"/topicos/{id}\"}[1m]) / rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", status=\"200\", uri=\"/topicos/{id}\"}[1m])",
       "legendFormat": "{{uri}} {{method}} {{status}}"
      },
      {
       "expr": "rate(http_server_requests_seconds_sum{application=\"$application\", instance=\"$instance\", status=\"200\", uri=\"/auth\"}[1m]) / rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", status=\"200\", uri=\"/auth\"}[1m])",
       "legendFormat": "{{uri}} {{method}} {{status}}"
      }
     ]
    },
    {
     "title": "MAX REQUEST DURATION",
     "type": "timeseries",
     "description": "Duração máxima de uma requisição",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "http_server_requests_seconds_max{application=\"$application\", instance=\"$instance\", status=\"200\", uri!=\"/actuator/prometheus\"}",
       "legendFormat": "{{uri}} {{method}} {{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "API USE",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "HEAP USED",
     "type": "gauge",
     "description": "Memória heap utilizada",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area = \"heap\"}) / sum(jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", area = \"heap\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "timeseries",
     "description": "Utilização de CPU",
     "gridPos": { "h": 7, "w": 20, "x": 4, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "system_cpu_usage{application=\"$application\", instance=\"$instance\"}",
       "legendFormat": "System CPU usage"
      },
      {
       "expr": "process_cpu_usage{application=\"$application\", instance=\"$instance\"}",
       "legendFormat": "Process CPU usage"
      }
     ]
    },
    {
     "title": "NON-HEAP USED",
     "type": "gauge",
     "description": "Memória non-heap utilizada",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{application=\"$application\", instance=\"$instance\", area = \"nonheap\"}) / sum(jvm_memory_max_bytes{application=\"$application\", instance=\"$instance\", area = \"nonheap\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "LOAD AVERAGE",
     "type": "timeseries",
     "description": "Quantidade média de processos em fila e em execução no último minuto e contagem de CPUs",
     "gridPos": { "h": 7, "w": 20, "x": 4, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "system_load_average_1m{application=\"$application\", instance=\"$instance\"}",
       "legendFormat": "Load average [1m]"
      },
      {
       "expr": "system_cpu_count{application=\"$application\", instance=\"$instance\"}",
       "legendFormat": "CPU core size"
      }
     ]
    }
   ]
  }
 ]
}